import { Header } from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Layout } from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`antialiased text-slate-500 dark:text-slate-400 bg-zinc-50 dark:bg-slate-900 h-full min-h-screen ${inter.className}`}
			>
				<Header />
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
